# Generated by Django 5.2.12 on 2026-03-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
