# Generated by Django 5.2.12 on 2026-04-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_productcatalog_max_price_productcatalog_min_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Leaf', max_length=50)),
                ('color', models.CharField(default='#dcfce7', max_length=20)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
