# Generated by Django 5.2.12 on 2026-04-01 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='market.category'),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_catalog_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price per unit (DA)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price per unit (DA)', max_digits=10, null=True),
        ),
    ]
