# Generated by Django 5.2.12 on 2026-04-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
