# Generated by Django 5.2.12 on 2026-04-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_productcatalog_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='image_url',
        ),
    ]
