# Generated by Django 5.2.12 on 2026-04-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_remove_productcatalog_image_url'),
        ('users', '0006_alter_farmerprofile_farm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.farm'),
        ),
    ]
