# Generated by Django 6.0.3 on 2026-04-18 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_remove_productcatalog_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=100)),
                ('usage_instructions', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('expected_available_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'EQUIPMENT_PROVIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
