# Generated by Django 5.2.12 on 2026-04-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('market', '0014_product_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farms.farm'),
        ),
    ]
