# Generated by Django 5.2.12 on 2026-04-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_product_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_images/'),
        ),
    ]
