# Generated by Django 5.2.12 on 2026-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_product_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Issue'), ('payment', 'Payment'), ('delivery', 'Delivery Issue'), ('product', 'Product Quality'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
