# Generated by Django 6.0.3 on 2026-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_equipmentbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='rental_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='requested_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
