# Generated by Django 5.2.12 on 2026-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_productcatalog_image'),
        ('market', '0018_equipmentbooking_expected_return_date_and_more'),
    ]

    operations = [
    ]
