# Generated by Django 5.2.12 on 2026-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_merge_20260423_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
