# Generated by Django 5.2.12 on 2026-04-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_product_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_approved',
        ),
    ]
