# Generated by Django 5.2.12 on 2026-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_remove_product_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CHARGING', 'In Charging'), ('IN_TRANSIT', 'In Transit'), ('NEAR_ARRIVAL', 'Close to Arrival'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
