# Generated by Django 5.2.12 on 2026-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_remove_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order Update'), ('PRICE', 'Price Regulation'), ('USER', 'New User'), ('FARM', 'New Farm'), ('COMPLAINT', 'New Complaint'), ('DELIVERY', 'Delivery Update'), ('GENERAL', 'General Alert')], default='GENERAL', max_length=20),
        ),
    ]
