# Generated by Django 5.2.12 on 2026-04-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_alter_order_status'),
        ('market', '0022_notification_notification_type'),
    ]

    operations = [
    ]
