# Generated by Django 5.2.12 on 2026-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_merge_20260428_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
