# Generated by Django 5.2.12 on 2026-04-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_merge_20260428_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
