# Generated by Django 5.2.12 on 2026-05-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_remove_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='season',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter')], default='SPRING', max_length=20),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='season',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter')], default='SPRING', max_length=20),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
