# Generated by Django 5.2.12 on 2026-05-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_pricehistory_season_pricehistory_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ON_WAY', 'On Way to Farm'), ('CHARGING', 'Loading'), ('NEAR_ARRIVAL', 'Close to Arrival'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
