# Generated by Django 5.2.12 on 2026-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_product_quality_grade_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
