# Generated by Django 5.2.12 on 2026-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_alter_notification_options_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
