# Generated by Django 5.2.12 on 2026-05-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_alter_notification_options_remove_notification_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
