# Generated by Django 5.2.12 on 2026-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0032_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("ON_WAY", "On Way to Farm"),
                    ("CHARGING", "Loading"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
