# Generated by Django 5.2.12 on 2026-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0033_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="battery_capacity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="charging_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="flight_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="is_electric",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipment",
            name="max_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="payload_capacity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
