# Generated by Django 5.2.12 on 2026-05-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0034_equipment_battery_capacity_equipment_charging_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
