# Generated by Django 5.2.12 on 2026-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0035_product_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcatalog",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
