# Generated by Django 5.2.12 on 2026-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='commercial_register_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/buyers/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farmer_card_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmers/'),
        ),
        migrations.AddField(
            model_name='transporterprofile',
            name='car_license_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/transporters/car/'),
        ),
        migrations.AddField(
            model_name='transporterprofile',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/transporters/driving/'),
        ),
    ]
