# Generated by Django 5.2.12 on 2026-04-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_buyerprofile_commercial_register_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
