# Generated by Django 6.0.3 on 2026-04-18 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_buyerprofile_commercial_register_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FARMER', 'Farmer'), ('BUYER', 'Buyer'), ('TRANSPORTER', 'Transporter'), ('EQUIPMENT_PROVIDER', 'Equipment Provider')], default='FARMER', max_length=50),
        ),
        migrations.CreateModel(
            name='EquipmentProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('commercial_register_file', models.FileField(blank=True, null=True, upload_to='documents/equipment_providers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
