# Generated by Django 5.2.12 on 2026-04-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_product_farm'),
        ('users', '0006_alter_farmerprofile_farm_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
