# Generated by Django 5.2.12 on 2026-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_equipmentproviderprofile'),
        ('users', '0007_delete_farm'),
    ]

    operations = [
    ]
