# Generated by Django 5.2.12 on 2026-04-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_address_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
