# Generated by Django 5.2.12 on 2026-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
